import fs from "node:fs/promises";
import { Presentation, PresentationFile } from "@oai/artifact-tool";

const out = "artifacts/slides";
const p = Presentation.create({ slideSize: { width: 1280, height: 720 } });
const C = {ink:"#13212E",blue:"#075985",sky:"#EAF5FA",line:"#CBD5E1",muted:"#51606D",green:"#0F766E",orange:"#B45309",white:"#FFFFFF"};
function text(slide, value, x,y,w,h,size=22,color=C.ink,bold=false){const s=slide.shapes.add({geometry:"textbox",position:{left:x,top:y,width:w,height:h},fill:"none",line:{style:"solid",fill:"none",width:0}});s.text=value;s.text.style={fontSize:size,color,bold};return s;}
function box(slide,x,y,w,h,fill=C.white){return slide.shapes.add({geometry:"roundRect",position:{left:x,top:y,width:w,height:h},fill,line:{style:"solid",fill:C.line,width:1},borderRadius:"rounded-xl"});}
function title(slide,kicker,headline){text(slide,kicker.toUpperCase(),72,48,400,24,12,C.blue,true);text(slide,headline,72,82,1100,64,36,C.ink,true);}
function footer(slide,n){text(slide,"Evidence-Grounded AI Governance Copilot-RAG",72,686,480,16,10,C.muted);text(slide,String(n).padStart(2,"0"),1170,686,36,16,10,C.muted,true);}
function bullet(slide,items,x,y,w){items.forEach((i,k)=>{text(slide,"•",x,y+k*48,16,24,20,C.blue,true);text(slide,i,x+22,y+k*48,w-22,36,18,C.ink);});}
let s=p.slides.add();s.background.fill=C.ink;text(s,"EVIDENCE-GROUNDED RAG",72,64,440,26,14,"#7DD3FC",true);text(s,"AI Governance\nCopilot",72,142,650,160,58,C.white,true);text(s,"A citation-enforced decision-support system for AI governance and agentic security.",72,334,530,72,23,"#D9E6EE");box(s,806,124,330,338,"#123047");text(s,"RELEASE GATE",840,166,240,26,14,"#7DD3FC",true);text(s,"No evidence\nNo answer",840,210,250,96,36,C.white,true);text(s,"Every claim must map to a precise, retrieved source excerpt.",840,330,235,54,17,"#D9E6EE");footer(s,1);
s=p.slides.add();title(s,"Decision", "Approve a governed RAG foundation, not a fluent search demo");bullet(s,["Target: AI governance and agentic-security evidence from approved NIST and OWASP releases.","Control: unsupported claims are rejected before users see an answer.","Outcome: measurable quality, reproducible releases, and audit-ready source provenance."],92,188,1010);footer(s,2);
s=p.slides.add();title(s,"Architecture", "A controlled workflow separates recall, precision, and grounding");const labels=["Normalize","Hybrid retrieve\n30 candidates","Cross-encoder\nrerank","Evidence gate","Generate structured\nclaims","Validate citations\nor abstain"];labels.forEach((l,i)=>{const x=72+i*190;box(s,x,232,158,110,i===3?"#FFF7ED":C.white);text(s,l,x+16,255,126,58,16,i===3?C.orange:C.ink,true);if(i<5)text(s,"→",x+162,270,24,30,22,C.blue,true);});text(s,"LangGraph makes every branch observable, replayable, and policy-controlled.",72,430,820,28,20,C.muted);footer(s,3);
s=p.slides.add();title(s,"Retrieval", "Weaviate delivers native hybrid retrieval with less custom search risk");box(s,72,180,520,360,C.sky);text(s,"Dense semantic search",108,220,280,30,25,C.blue,true);text(s,"bge-large-en-v1.5 captures meaning and paraphrase.",108,264,400,52,18,C.ink);text(s,"BM25 keyword match",108,334,280,30,25,C.blue,true);text(s,"Preserves exact frameworks, functions, and security terminology.",108,378,400,52,18,C.ink);box(s,640,180,560,360,C.white);text(s,"Why not ChromaDB for production?",676,220,430,30,25,C.ink,true);bullet(s,["Weaviate fuses vector + BM25 natively.","Scores and filters stay in one query surface.","Reranking integrates without a separate BM25 service."],676,276,470);footer(s,4);
s=p.slides.add();title(s,"Grounding", "Citation enforcement is a release gate, not a prompt suggestion");const rows=[["1","Structured answer","Atomic claims + chunk IDs + exact quote spans"],["2","Deterministic validator","Rejects unknown chunks, missing spans, and uncited claims"],["3","Independent verifier","Checks entailment and contradictions before release"],["4","Safe fallback","One revise attempt; otherwise a clear abstention"]];rows.forEach((r,i)=>{box(s,72,176+i*94,1130,72,i===3?"#FFF7ED":C.white);text(s,r[0],96,198+i*94,30,26,18,C.blue,true);text(s,r[1],152,198+i*94,260,28,20,C.ink,true);text(s,r[2],438,198+i*94,710,32,17,C.muted);});footer(s,5);
s=p.slides.add();title(s,"Quality", "The 200-case benchmark converts RAG quality into a build contract");const metrics=[["Faithfulness","≥ 0.95"],["Citation validity","100%"],["Answer correctness","≥ 0.85"],["Abstention F1","≥ 0.90"]];metrics.forEach((m,i)=>{box(s,72+i*278,214,238,150,C.white);text(s,m[0],96+i*278,244,190,28,17,C.muted,true);text(s,m[1],96+i*278,291,180,42,29,C.green,true);});text(s,"110 direct facts  •  45 multi-source questions  •  25 retrieval-stress cases  •  20 unanswerable cases",72,432,1040,28,20,C.ink);text(s,"A build also fails on a >2-point regression from the approved baseline.",72,480,880,28,19,C.orange,true);footer(s,6);
s=p.slides.add();title(s,"Governance", "Corpus and prompt changes are versioned releases with evidence");bullet(s,["Source manifest records URL, license, version, checksum, page/section, and corpus release ID.","Prompts and retrieval settings are reviewed YAML with semantic versions and change logs.","New source material is staged, evaluated, approved, and promoted - never silently overwritten."],92,188,1010);footer(s,7);
s=p.slides.add();title(s,"Delivery", "A Docker Compose-first delivery path makes the system demonstrable and portable");const layers=[["React / Next.js","Answer, citations, excerpts, diagnostics, abstention"],["FastAPI + LangGraph","Query, ingestion, evaluation, health, trace APIs"],["Weaviate + model adapters","Hybrid retrieval, rerank, OmniRoute/direct-provider fallback"],["CI quality gate","Tests, benchmark, diagnostics, scheduled validation"]];layers.forEach((r,i)=>{box(s,160,168+i*92,960,66,i===3?"#E0F2FE":C.white);text(s,r[0],192,188+i*92,300,26,19,C.blue,true);text(s,r[1],510,188+i*92,570,26,17,C.ink);});footer(s,8);
s=p.slides.add();title(s,"Backlog", "Delivery is governed through a Kanban SDLC board");const cols=["Backlog","Ready","In Progress","Review","Test","Done"];cols.forEach((c,i)=>{box(s,72+i*188,188,164,315,i===0?"#EAF5FA":C.white);text(s,c,88+i*188,210,140,26,17,C.ink,true);text(s,i<2?"Foundation\nIngestion\nRetrieval\nGrounding\nAPI\nUI\nCI":i===2?"Build in\nsmall slices":"Evidence\nrequired",88+i*188,260,130,110,16,C.muted);});text(s,"Airtable import file defines 15 implementation tickets with acceptance criteria and dependencies.",72,552,960,26,18,C.muted);footer(s,9);
s=p.slides.add();title(s,"Risk controls", "Known risks have explicit ownership and failure paths");const risks=[["Corpus drift","Versioned approval and release isolation"],["Provider outage","OmniRoute health check plus direct-provider fallback"],["Hallucinated citations","Exact quote-span validation and abstention"],["Metric gaming","40 CI-only cases and regression diagnostics"]];risks.forEach((r,i)=>{box(s,72,176+i*84,1130,62,C.white);text(s,r[0],96,194+i*84,300,24,19,C.orange,true);text(s,r[1],460,194+i*84,680,24,18,C.ink);});footer(s,10);
s=p.slides.add();title(s,"Recommendation", "Approve the foundation and use the quality gate to earn production readiness");text(s,"The project is ready to move from architecture to an evidence-backed prototype.",72,184,940,36,25,C.ink);bullet(s,["Stand up the Compose stack and curated corpus release.","Run the full benchmark before accepting retrieval or prompt changes.","Use the Kanban board to deliver auditable increments."],92,278,980);text(s,"Success is not a persuasive answer - it is a supported answer or an honest abstention.",72,536,1020,36,23,C.blue,true);footer(s,11);
await fs.mkdir(out,{recursive:true});for(const [i,slide] of p.slides.items.entries()){const blob=await p.export({slide,format:"png",scale:1});await fs.writeFile(`${out}/slide-${String(i+1).padStart(2,"0")}.png`,new Uint8Array(await blob.arrayBuffer()));}const deck=await PresentationFile.exportPptx(p);await deck.save(`${out}/evidence_grounded_rag_leadership_deck.pptx`);
